
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 01 20:05:33 EDT 2010
//----------------------------------------------------

package edu.wpi.margrave;

/** CUP generated class containing symbol constants. */
public class MCommandSym {
  /* terminals */
  public static final int AT = 74;
  public static final int PRIORITY = 68;
  public static final int IDENTIFIER = 79;
  public static final int COLLAPSE = 25;
  public static final int PREDICATE = 47;
  public static final int NATURAL = 80;
  public static final int REQUEST = 76;
  public static final int TARGET = 46;
  public static final int XACML = 61;
  public static final int GET = 63;
  public static final int NEXT = 71;
  public static final int QUALIFIED = 70;
  public static final int QUIT = 78;
  public static final int COMMA = 18;
  public static final int RPAREN = 10;
  public static final int EXPLORE = 2;
  public static final int ALL = 13;
  public static final int VECTOR = 77;
  public static final int UNDER = 19;
  public static final int LPAREN = 9;
  public static final int CHILD = 75;
  public static final int COMPARE = 26;
  public static final int NOT = 5;
  public static final int ATMOSTONE = 39;
  public static final int PUBLISH = 17;
  public static final int SUBSET = 44;
  public static final int UNPOPULATED = 29;
  public static final int DISJOINT = 36;
  public static final int ABSTRACT = 43;
  public static final int PARTIAL = 40;
  public static final int GUARANTEEDQMARK = 72;
  public static final int POPULATED = 28;
  public static final int ONE = 14;
  public static final int HIGHER = 67;
  public static final int RCOMBINE = 57;
  public static final int FOR = 30;
  public static final int ADD = 32;
  public static final int LOAD = 60;
  public static final int OTHERVAR = 54;
  public static final int SHOW = 12;
  public static final int PCOMBINE = 58;
  public static final int EOF = 0;
  public static final int TOTAL = 42;
  public static final int COUNT = 64;
  public static final int FUNCTION = 41;
  public static final int VOCABULARY = 51;
  public static final int INFO = 24;
  public static final int IS = 15;
  public static final int IN = 73;
  public static final int DEBUG = 21;
  public static final int OR = 4;
  public static final int CEILING = 22;
  public static final int RULES = 66;
  public static final int SET = 45;
  public static final int error = 1;
  public static final int SINGLETON = 38;
  public static final int RULE = 48;
  public static final int DECISION = 52;
  public static final int SQS = 62;
  public static final int COLON = 6;
  public static final int NONEMPTY = 37;
  public static final int CASES = 31;
  public static final int CREATE = 50;
  public static final int POSSIBLEQMARK = 16;
  public static final int PREPARE = 59;
  public static final int IDBOUTPUT = 27;
  public static final int RENAME = 23;
  public static final int LEAF = 56;
  public static final int TUPLING = 20;
  public static final int SIZE = 65;
  public static final int POLICY = 55;
  public static final int AND = 3;
  public static final int SORT = 34;
  public static final int TO = 49;
  public static final int IMPLIES = 7;
  public static final int SUBSORT = 33;
  public static final int REQUESTVAR = 53;
  public static final int IFF = 8;
  public static final int CONSTRAINT = 35;
  public static final int THAN = 69;
  public static final int EQUALS = 11;
}

