
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 09 14:31:50 EDT 2010
//----------------------------------------------------

package edu.wpi.margrave;

/** CUP generated class containing symbol constants. */
public class MJunosSym {
  /* terminals */
  public static final int PREFIXLISTFILTER = 27;
  public static final int APPLYGROUPS = 25;
  public static final int IPV6 = 42;
  public static final int LBRACKET = 38;
  public static final int REJECT = 30;
  public static final int IPV4 = 41;
  public static final int COMMENT = 43;
  public static final int DESTINATIONADDRESS = 16;
  public static final int INTERFACE = 21;
  public static final int SOURCEADDRESS = 17;
  public static final int FILTER = 9;
  public static final int DESTINATIONPREFIXLIST = 15;
  public static final int NEXTHOP = 28;
  public static final int LOCALPREFERENCE = 22;
  public static final int SOURCEPREFIXLIST = 14;
  public static final int SEMICOLON = 39;
  public static final int PROTOCOL = 20;
  public static final int DESTINATIONPORT = 18;
  public static final int NEXTHEADER = 13;
  public static final int VERSION = 2;
  public static final int ROUTEFILTER = 26;
  public static final int ORLONGER = 29;
  public static final int PREFIXLIST = 12;
  public static final int SOURCEPORT = 19;
  public static final int EOF = 0;
  public static final int POLICYOPTIONS = 3;
  public static final int GROUP = 11;
  public static final int RBRACKET = 37;
  public static final int error = 1;
  public static final int COMMUNITY = 24;
  public static final int DISCARD = 33;
  public static final int FROM = 6;
  public static final int LOG = 34;
  public static final int FIREWALL = 10;
  public static final int LBRACE = 35;
  public static final int ACCEPT = 31;
  public static final int FAMILY = 8;
  public static final int POLICYSTATEMENT = 4;
  public static final int RBRACE = 36;
  public static final int THEN = 7;
  public static final int COUNT = 32;
  public static final int TERM = 5;
  public static final int ASPATH = 23;
  public static final int IDENTIFIER = 40;
}

