#!/bin/sh
# Margrave build script

MARGRAVE_PROJECT_ROOT=`pwd`
echo Beginning build at Margrave root directory: ${MARGRAVE_PROJECT_ROOT}

##############################

echo Removing old files...

rm -rf ${MARGRAVE_PROJECT_ROOT}/build-temp

##############################
echo Copying files for build...

mkdir ${MARGRAVE_PROJECT_ROOT}/build-temp
cd ${MARGRAVE_PROJECT_ROOT}/build-temp
mkdir margrave
mkdir margrave/lib
mkdir margrave/tests
mkdir margrave/examples
mkdir margrave/scribblings
mkdir margrave/licenses


cp ${MARGRAVE_PROJECT_ROOT}/racket/*.rkt margrave

cp ${MARGRAVE_PROJECT_ROOT}/licenses/* margrave/licenses

cp ${MARGRAVE_PROJECT_ROOT}/java/lib/*.jar margrave/lib

cp ${MARGRAVE_PROJECT_ROOT}/racket/scribblings/*.scrbl margrave/scribblings

cp ${MARGRAVE_PROJECT_ROOT}/racket/tests/*.rkt margrave/tests
cp ${MARGRAVE_PROJECT_ROOT}/racket/tests/*.p margrave/tests
cp ${MARGRAVE_PROJECT_ROOT}/racket/tests/*.v margrave/tests

# examples need updating
cp -r ${MARGRAVE_PROJECT_ROOT}/racket/examples/* margrave/examples

##############################

echo Building fresh Java .class files...

# !!!!!!!!!!!!!!!!!!!!!!!!!!!
# MAKE CHANGES TO JAVA OPTIONS HERE:
VERBOSE=0
DEBUG=1

MJLIB=${MARGRAVE_PROJECT_ROOT}/build-temp/margrave/lib

# -verbose for verbose compiler output
# -g to include debugging info

if [ $VERBOSE = 1 ]; then
    VFLAG="-verbose"
else
    VFLAG=""
fi

if [ $DEBUG = 1 ]; then
    DFLAG="-g"
else
    DFLAG=""
fi

# Force compatability with JRE 1.6. 

JAVA_C="javac -target 1.6 -source 1.6 $VFLAG $DFLAG -classpath ${MJLIB}:.:${MJLIB}/kodkod.jar:${MJLIB}/sunxacml.jar:${MJLIB}/json.jar:${MJLIB}/org.sat4j.core.jar:${MJLIB}/commons-io-2.0.1.jar -d ${MJLIB}"
${JAVA_C} ${MARGRAVE_PROJECT_ROOT}/java/src/edu/wpi/margrave/*.java

# JAR the class files
# Note that NOT cding and using ${MJLIB}/edu would not give us the desired outcome.
cd ${MJLIB}
jar cf ${MJLIB}/margrave.jar edu
# Add the v option for verbose output.

# Clean up by removing all class files
rm -r ${MJLIB}/edu

# Copy a fresh version of the .jar files to
# the DEVELOPMENT folder. Git will ignore.

mkdir ${MARGRAVE_PROJECT_ROOT}/racket/lib
cp ${MJLIB}/*.jar ${MARGRAVE_PROJECT_ROOT}/racket/lib

##############################
echo Creating PLT archive for distribution
# Need to CD to appropriate folder again:
cd ${MARGRAVE_PROJECT_ROOT}/build-temp
raco pack --replace --at-plt testbuild.plt margrave

##############################
echo "Don't forget to insert safety checks. Did compilation complete ok? etc."
echo "Also can we build in the date?"

