#!/bin/sh
# Margrave build script

MARGRAVE_PROJECT_ROOT=`pwd`
echo Beginning build at Margrave root directory: ${MARGRAVE_PROJECT_ROOT}

##############################

echo Removing old files...

rm -rf ${MARGRAVE_PROJECT_ROOT}/build-temp

##############################
echo Copying files for build...

mkdir ${MARGRAVE_PROJECT_ROOT}/build-temp
cd ${MARGRAVE_PROJECT_ROOT}/build-temp
mkdir margrave
mkdir margrave/bin
mkdir margrave/tests
mkdir margrave/examples
mkdir margrave/scribblings
mkdir margrave/licenses


cp ${MARGRAVE_PROJECT_ROOT}/racket/*.rkt margrave

cp ${MARGRAVE_PROJECT_ROOT}/licenses/* margrave/licenses

cp ${MARGRAVE_PROJECT_ROOT}/java/lib/*.jar margrave/bin

cp ${MARGRAVE_PROJECT_ROOT}/racket/scribblings/*.scrbl margrave/scribblings

cp ${MARGRAVE_PROJECT_ROOT}/racket/tests/*.rkt margrave/tests
cp ${MARGRAVE_PROJECT_ROOT}/racket/tests/*.p margrave/tests
cp ${MARGRAVE_PROJECT_ROOT}/racket/tests/*.v margrave/tests

# examples need updating
cp -r ${MARGRAVE_PROJECT_ROOT}/racket/examples/* margrave/examples

##############################

echo Building fresh Java .class files...

# !!!!!!!!!!!!!!!!!!!!!!!!!!!
# MAKE CHANGES TO JAVA OPTIONS HERE:
VERBOSE=0
DEBUG=1

mkdir margrave/bin/edu
mkdir margrave/bin/edu/wpi
mkdir margrave/bin/edu/wpi/margrave

MJLIB=${MARGRAVE_PROJECT_ROOT}/build-temp/margrave/bin

# -verbose for verbose compiler output
# -g to include debugging info

if [ $VERBOSE = 1 ]; then
    VFLAG="-verbose"
else
    VFLAG=""
fi

if [ $DEBUG = 1 ]; then
    DFLAG="-g"
else
    DFLAG=""
fi

JAVA_C="javac $VFLAG $DFLAG -classpath ${MJLIB}:.:${MJLIB}/kodkod.jar:${MJLIB}/sunxacml.jar:${MJLIB}/json.jar:${MJLIB}/org.sat4j.core.jar:${MJLIB}/commons-io-2.0.1.jar -d ${MJLIB}"
${JAVA_C} ${MARGRAVE_PROJECT_ROOT}/java/src/edu/wpi/margrave/*.java

# Copy a fresh version of these .class and .jar files into 
# the DEVELOPMENT folder. Git will ignore.

mkdir ${MARGRAVE_PROJECT_ROOT}/racket/bin
mkdir ${MARGRAVE_PROJECT_ROOT}/racket/bin/edu
mkdir ${MARGRAVE_PROJECT_ROOT}/racket/bin/edu/wpi
mkdir ${MARGRAVE_PROJECT_ROOT}/racket/bin/edu/wpi/margrave
cp ${MJLIB}/edu/wpi/margrave/*.class ${MARGRAVE_PROJECT_ROOT}/racket/bin/edu/wpi/margrave

##############################
echo Creating PLT archive for distribution
raco pack --replace --at-plt testbuild.plt margrave

##############################
echo "Don't forget to insert safety checks. Did compilation complete ok? etc."
echo "Also can we build in the date?"
echo "todo make a jar, not individual class files"

