(Policy BigFW uses BigFirewallPolicy
	(Target )
	(Rules
       
         (Rule0 = (Accept ipsrc ipdest portsrc portdest) :- (ip00 ipdest) (port00 portdest))
         (Rule1 = (Accept ipsrc ipdest portsrc portdest) :- (ip01 ipdest) (port00 portdest))
         (Rule2 = (Accept ipsrc ipdest portsrc portdest) :- (ip02 ipdest) (port00 portdest))         
         (Rule3 = (Accept ipsrc ipdest portsrc portdest) :- (ip03 ipdest) (port00 portdest))
         (Rule4 = (Accept ipsrc ipdest portsrc portdest) :- (ip04 ipdest) (port00 portdest))
         (Rule5 = (Accept ipsrc ipdest portsrc portdest) :- (ip05 ipdest) (port00 portdest))
         (Rule6 = (Accept ipsrc ipdest portsrc portdest) :- (ip06 ipdest) (port00 portdest))
         (Rule7 = (Accept ipsrc ipdest portsrc portdest) :- (ip07 ipdest) (port00 portdest))
         (Rule8 = (Accept ipsrc ipdest portsrc portdest) :- (ip08 ipdest) (port00 portdest))
         (Rule9 = (Accept ipsrc ipdest portsrc portdest) :- (ip09 ipdest) (port00 portdest))

         (Rule10 = (Accept ipsrc ipdest portsrc portdest) :- (ip10 ipdest) (port01 portdest))
         (Rule11 = (Accept ipsrc ipdest portsrc portdest) :- (ip11 ipdest) (port01 portdest))
         (Rule12 = (Accept ipsrc ipdest portsrc portdest) :- (ip12 ipdest) (port01 portdest))         
         (Rule13 = (Accept ipsrc ipdest portsrc portdest) :- (ip13 ipdest) (port01 portdest))
         (Rule14 = (Accept ipsrc ipdest portsrc portdest) :- (ip14 ipdest) (port01 portdest))
         (Rule15 = (Accept ipsrc ipdest portsrc portdest) :- (ip15 ipdest) (port01 portdest))
         (Rule16 = (Accept ipsrc ipdest portsrc portdest) :- (ip16 ipdest) (port01 portdest))
         (Rule17 = (Accept ipsrc ipdest portsrc portdest) :- (ip17 ipdest) (port01 portdest))
         (Rule18 = (Accept ipsrc ipdest portsrc portdest) :- (ip18 ipdest) (port01 portdest))
         (Rule19 = (Accept ipsrc ipdest portsrc portdest) :- (ip19 ipdest) (port01 portdest))
         
         (Rule20 = (Accept ipsrc ipdest portsrc portdest) :- (ip20 ipdest) (port02 portdest))
         (Rule21 = (Accept ipsrc ipdest portsrc portdest) :- (ip21 ipdest) (port02 portdest))
         (Rule22 = (Accept ipsrc ipdest portsrc portdest) :- (ip22 ipdest) (port02 portdest))         
         (Rule23 = (Accept ipsrc ipdest portsrc portdest) :- (ip23 ipdest) (port02 portdest))
         (Rule24 = (Accept ipsrc ipdest portsrc portdest) :- (ip24 ipdest) (port02 portdest))
         (Rule25 = (Accept ipsrc ipdest portsrc portdest) :- (ip25 ipdest) (port02 portdest))
         (Rule26 = (Accept ipsrc ipdest portsrc portdest) :- (ip26 ipdest) (port02 portdest))
         (Rule27 = (Accept ipsrc ipdest portsrc portdest) :- (ip27 ipdest) (port02 portdest))
         (Rule28 = (Accept ipsrc ipdest portsrc portdest) :- (ip28 ipdest) (port02 portdest))
         (Rule29 = (Accept ipsrc ipdest portsrc portdest) :- (ip29 ipdest) (port02 portdest))

         (Rule30 = (Accept ipsrc ipdest portsrc portdest) :- (ip30 ipdest) (port03 portdest))
         (Rule31 = (Accept ipsrc ipdest portsrc portdest) :- (ip31 ipdest) (port03 portdest))
         (Rule32 = (Accept ipsrc ipdest portsrc portdest) :- (ip32 ipdest) (port03 portdest))         
         (Rule33 = (Accept ipsrc ipdest portsrc portdest) :- (ip33 ipdest) (port03 portdest))
         (Rule34 = (Accept ipsrc ipdest portsrc portdest) :- (ip34 ipdest) (port03 portdest))
         (Rule35 = (Accept ipsrc ipdest portsrc portdest) :- (ip35 ipdest) (port03 portdest))
         (Rule36 = (Accept ipsrc ipdest portsrc portdest) :- (ip36 ipdest) (port03 portdest))
         (Rule37 = (Accept ipsrc ipdest portsrc portdest) :- (ip37 ipdest) (port03 portdest))
         (Rule38 = (Accept ipsrc ipdest portsrc portdest) :- (ip38 ipdest) (port03 portdest))
         (Rule39 = (Accept ipsrc ipdest portsrc portdest) :- (ip39 ipdest) (port03 portdest))

         (Rule40 = (Accept ipsrc ipdest portsrc portdest) :- (ip40 ipdest) (port04 portdest))
         (Rule41 = (Accept ipsrc ipdest portsrc portdest) :- (ip41 ipdest) (port04 portdest))
         (Rule42 = (Accept ipsrc ipdest portsrc portdest) :- (ip42 ipdest) (port04 portdest))         
         (Rule43 = (Accept ipsrc ipdest portsrc portdest) :- (ip43 ipdest) (port04 portdest))
         (Rule44 = (Accept ipsrc ipdest portsrc portdest) :- (ip44 ipdest) (port04 portdest))
         (Rule45 = (Accept ipsrc ipdest portsrc portdest) :- (ip45 ipdest) (port04 portdest))
         (Rule46 = (Accept ipsrc ipdest portsrc portdest) :- (ip46 ipdest) (port04 portdest))
         (Rule47 = (Accept ipsrc ipdest portsrc portdest) :- (ip47 ipdest) (port04 portdest))
         (Rule48 = (Accept ipsrc ipdest portsrc portdest) :- (ip48 ipdest) (port04 portdest))
         (Rule49 = (Accept ipsrc ipdest portsrc portdest) :- (ip49 ipdest) (port04 portdest))

         
         ; This rule always applies
         (RuleX = (Drop ipsrc ipdest portsrc portdest) :- (IPAddress ipsrc))
                )
                
	(RComb FAC)
	(PComb FAC)
	(Children ))
