#!/bin/bash
###!/usr/local/bin/bash
# adjust the above depending on `which bash`
# iptables Configuration Modeling
# Copyright (C) Christopher Barratt 2010 All rights reserved.
#
#  This file is part of Margrave.
#
#  Margrave is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Margrave is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Margrave.  If not, see <http://www.gnu.org/licenses/>.


# TN: create the policy read-protected
touch iptables-firewall.p
chmod og-r iptables-firewall.p

echo "(Policy iptables-firewall uses iptables-firewall" \
     "  (Target)" \
     "  (Rules" >> iptables-firewall.p

$1

echo ")" \
     "(RComb FAC)" \
     "(PComb FAC)" \
     "(Children))" >> iptables-firewall.p
